# Generated by Django 5.2.17 on 2026-08-31 19:36

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("normal", "Normal"), ("read_only", "Read-only")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("media_moderation_active", models.BooleanField(default=True)),
                (
                    "geo_restrict_writes_to_algeria",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, only requests whose IP geolocates to Algeria may create/edit listings (admins always bypass this). Turn off if this blocks legitimate diaspora volunteers coordinating from abroad.",
                    ),
                ),
            ],
            options={
                "verbose_name": "App configuration",
                "verbose_name_plural": "App configuration",
            },
        ),
        migrations.CreateModel(
            name="DisasterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name/emoji shown in the UI",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_phone", models.CharField(max_length=30)),
                (
                    "related_listing_description",
                    models.CharField(blank=True, max_length=200),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("processed", "Processed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wilaya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("centroid_latitude", models.FloatField(blank=True, null=True)),
                ("centroid_longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200)),
                ("target_description", models.CharField(blank=True, max_length=300)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status_changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "disaster_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.disastertype",
                    ),
                ),
                (
                    "authorized_wilayas",
                    models.ManyToManyField(
                        blank=True, related_name="campaigns", to="core.wilaya"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        default=core.models.generate_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("pii_obfuscated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "obfuscated_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin", "Admin"),
                            ("creator", "Creator"),
                            ("responder", "Responder"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("estimated_quantity", models.CharField(blank=True, max_length=200)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("commune", models.CharField(blank=True, max_length=200)),
                ("location_description", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "position_accuracy",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("approximate", "Approximate (no exact GPS position)"),
                        ],
                        default="approximate",
                        max_length=20,
                    ),
                ),
                ("contact_last_name", models.CharField(max_length=100)),
                ("contact_first_name", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=30)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_date_of_birth", models.DateField()),
                (
                    "organization_or_person_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "media_file",
                    models.FileField(blank=True, null=True, upload_to="need_media/"),
                ),
                (
                    "media_moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=10,
                    ),
                ),
                ("is_cancelled", models.BooleanField(default=False)),
                ("cancellation_reason", models.CharField(blank=True, max_length=500)),
                (
                    "covered_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of active (en_route/delivered) pickups, an approximate visual indicator only.",
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("partially_covered", "Partially covered"),
                            ("covered", "Covered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "location_viewer_share_token",
                    models.CharField(
                        default=core.models.generate_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("edit_history", models.JSONField(blank=True, default=list)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="needs",
                        to="core.campaign",
                    ),
                ),
                (
                    "disaster_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.disastertype",
                    ),
                ),
                (
                    "wilaya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="needs",
                        to="core.wilaya",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DamagePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="damage_photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_photos",
                        to="core.need",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        default=core.models.generate_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("pii_obfuscated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "obfuscated_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin", "Admin"),
                            ("creator", "Creator"),
                            ("responder", "Responder"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "responder_type",
                    models.CharField(
                        choices=[
                            ("individual_volunteer", "Individual volunteer"),
                            ("organization", "Organization"),
                            ("collective_truck", "Collective truck"),
                        ],
                        max_length=30,
                    ),
                ),
                ("responder_last_name", models.CharField(max_length=100)),
                ("responder_first_name", models.CharField(max_length=100)),
                ("responder_phone", models.CharField(max_length=30)),
                ("responder_email", models.EmailField(blank=True, max_length=254)),
                ("responder_date_of_birth", models.DateField()),
                (
                    "organization_or_person_name",
                    models.CharField(blank=True, max_length=200),
                ),
                ("content_brought", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_route", "En route"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="en_route",
                        max_length=20,
                    ),
                ),
                ("cancellation_reason", models.CharField(blank=True, max_length=500)),
                ("location_sharing_active", models.BooleanField(default=False)),
                ("pickup_date", models.DateTimeField(auto_now_add=True)),
                ("actual_delivery_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickups",
                        to="core.need",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_pings",
                        to="core.pickup",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="delivery_photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_photos",
                        to="core.pickup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgressUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("free_text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("gps_latitude", models.FloatField(blank=True, null=True)),
                ("gps_longitude", models.FloatField(blank=True, null=True)),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to="core.pickup",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
