# Generated by Django 5.2.17 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="need",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="need",
            name="voice_processing_error",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="need",
            name="voice_processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="ready",
                max_length=10,
            ),
        ),
    ]
