# Generated by Django 5.2.17 on 2026-09-11 21:56

import core.models
import django.db.models.deletion
from django.db import migrations, models


def backfill_precision_level(apps, schema_editor):
    """Every pre-existing CollectionPoint predates precision_level: an
    international one always carries an exact position (mandatory at
    creation, see CollectionPointCreateSerializer.validate) so it's
    PRECISION_EXACT; a national one is exact only when latitude was
    actually captured, PRECISION_CITY otherwise (the wilaya-centroid
    fallback CollectionPointMapPinSerializer already used before this
    field existed). Without this, every old row would default to "exact"
    and start claiming a GPS precision it never had."""
    CollectionPoint = apps.get_model("core", "CollectionPoint")
    CollectionPoint.objects.filter(country_code="", latitude__isnull=True).update(precision_level="city")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_need_voice_processing"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryCentroidCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="FlyerSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_creator_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_editor_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_creator_country",
                    models.CharField(
                        blank=True, editable=False, max_length=2, null=True
                    ),
                ),
                (
                    "audit_editor_country",
                    models.CharField(
                        blank=True, editable=False, max_length=2, null=True
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        default=core.models.generate_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("submitter_name", models.CharField(blank=True, max_length=200)),
                ("submitter_phone", models.CharField(blank=True, max_length=30)),
                ("flyer_image", models.ImageField(upload_to="flyer_submissions/")),
                (
                    "flyer_moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=10,
                    ),
                ),
                (
                    "flyer_moderated_by",
                    models.CharField(
                        blank=True,
                        choices=[("system", "System"), ("admin", "Admin")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("needs_review", "Needs review"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("failed", "Extraction failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_country", "No country identifiable on the flyer"),
                            (
                                "money_collection",
                                "Flyer solicits an online money transfer (CCP/IBAN/PayPal/cagnotte...)",
                            ),
                            (
                                "flyer_moderation",
                                "Flyer image failed content moderation",
                            ),
                            ("admin", "Rejected by an admin during review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_extracted_text", models.TextField(blank=True)),
                ("llm_raw_response", models.TextField(blank=True)),
                ("organization_common", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="flyer_extraction_active",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, the 'create a collection point from a flyer photo' feature calls the Gemini vision API (core.gemini_extraction) to read the flyer and propose one or more collection points for human review. If GEMINI_API_KEY isn't configured, the feature is unavailable regardless of this flag. Turn this off to disable flyer submissions entirely (e.g. API quota exhausted) without touching the manual creation forms, which are unaffected.",
            ),
        ),
        migrations.AddField(
            model_name="collectionpoint",
            name="city",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="collectionpoint",
            name="precision_level",
            field=models.CharField(
                choices=[
                    ("exact", "Exact address"),
                    ("city", "City only"),
                    ("country", "Country only"),
                ],
                default="exact",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ExtractedCollectionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("include_in_publish", models.BooleanField(default=True)),
                ("point_name", models.CharField(blank=True, max_length=200)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("country_name", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=150)),
                ("location_description", models.TextField(blank=True)),
                (
                    "precision_level",
                    models.CharField(
                        choices=[
                            ("exact", "Exact address"),
                            ("city", "City only"),
                            ("country", "Country only"),
                        ],
                        default="country",
                        max_length=10,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("hours", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("accepted_donations", models.TextField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("other_phones", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True, max_length=300)),
                ("tiktok_url", models.URLField(blank=True, max_length=300)),
                ("instagram_url", models.URLField(blank=True, max_length=300)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.collectionpoint",
                    ),
                ),
                (
                    "published_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.collectionpoint",
                    ),
                ),
                (
                    "wilaya",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.wilaya",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_points",
                        to="core.flyersubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(backfill_precision_level, migrations.RunPython.noop),
    ]
