# Generated by Django 5.2.17 on 2026-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="need",
            name="contact_date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="pickup",
            name="responder_date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
