# Generated by Django 5.2.17 on 2026-08-31 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_need_contact_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("need_media_file", "Need media file (audio/video)"),
                            ("damage_photo", "Damage photo"),
                            ("delivery_photo", "Delivery photo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("media_id", models.PositiveIntegerField()),
                ("reporter_name", models.CharField(max_length=200)),
                ("reporter_phone", models.CharField(max_length=30)),
                ("reason", models.CharField(max_length=500)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("processed", "Processed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="damagephoto",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="deliveryphoto",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="DuplicateReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporter_name", models.CharField(max_length=200)),
                ("reporter_phone", models.CharField(max_length=30)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("processed", "Processed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reference_need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reports_as_reference",
                        to="core.need",
                    ),
                ),
                (
                    "reported_need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reports_against",
                        to="core.need",
                    ),
                ),
            ],
        ),
    ]
