# Generated by Django 5.2.17 on 2026-09-11 22:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_flyer_extraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionpoint",
            name="flyer_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.collection_point_flyer_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="flyersubmission",
            name="flyer_image",
            field=models.ImageField(upload_to=core.models.flyer_submission_upload_path),
        ),
    ]
