# Generated by Django 5.2.17 on 2026-09-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_random_flyer_filenames"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flyersubmission",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_country", "No country identifiable on the flyer"),
                    (
                        "money_collection",
                        "Flyer solicits an online money transfer (CCP/IBAN/PayPal/cagnotte...)",
                    ),
                    ("flyer_moderation", "Flyer image failed content moderation"),
                    ("admin", "Rejected by an admin during review"),
                    (
                        "duplicate",
                        "Every extracted point matched an existing collection point",
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
