# Generated by Django 5.2.17 on 2026-09-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_collectionpoint_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="need",
            name="covered_quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Count of active (en_route/delivered) pickups. Internal counter for overall_status only -- not a ratio against estimated_quantity.",
            ),
        ),
    ]
