# Generated by Django 5.2.17 on 2026-09-25 12:26

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_flyer_auto_publish"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_creator_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_editor_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_creator_country",
                    models.CharField(
                        blank=True, editable=False, max_length=2, null=True
                    ),
                ),
                (
                    "audit_editor_country",
                    models.CharField(
                        blank=True, editable=False, max_length=2, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electricity", "Poteau / câble électrique dangereux"),
                            ("road", "Trou / route dégradée"),
                            ("lighting", "Éclairage public"),
                            ("water", "Fuite d'eau / égout"),
                            ("waste", "Déchets"),
                            ("signage", "Signalisation"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("commune", models.CharField(blank=True, max_length=200)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "position_source",
                    models.CharField(
                        choices=[("gps", "GPS"), ("manual", "Manual address")],
                        default="gps",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "voice_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.models.signalement_media_upload_path,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.models.signalement_media_upload_path,
                    ),
                ),
                (
                    "video_moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "video_moderated_by",
                    models.CharField(
                        blank=True,
                        choices=[("system", "System"), ("admin", "Admin")],
                        max_length=10,
                    ),
                ),
                ("voice_transcript", models.TextField(blank=True)),
                ("video_transcript", models.TextField(blank=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("ready", "Ready")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("processing_error", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("resolved", "Resolved")],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("category_suggested_by_ai", models.BooleanField(default=False)),
                ("confirmations_count", models.PositiveIntegerField(default=0)),
                ("fixed_reports_count", models.PositiveIntegerField(default=0)),
                (
                    "access_token",
                    models.CharField(
                        default=core.models.generate_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "wilaya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signalements",
                        to="core.wilaya",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignalementPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_creator_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_editor_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "audit_creator_country",
                    models.CharField(
                        blank=True, editable=False, max_length=2, null=True
                    ),
                ),
                (
                    "audit_editor_country",
                    models.CharField(
                        blank=True, editable=False, max_length=2, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.models.signalement_photo_upload_path
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "moderated_by",
                    models.CharField(
                        blank=True,
                        choices=[("system", "System"), ("admin", "Admin")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signalement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.signalement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
