# Generated by Django 5.2.17 on 2026-09-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_signalement"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="signalement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.signalement",
            ),
        ),
        migrations.AlterField(
            model_name="signalement",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_review", "In review"),
                    ("resolved", "Resolved"),
                    ("cancelled", "Cancelled"),
                ],
                default="new",
                max_length=10,
            ),
        ),
    ]
