# Generated by Django 5.2.17 on 2026-09-01 11:21
#
# Splits Need's single media_type/media_file (text OR audio OR video, one
# choice) into independent voice_file and video_file fields that can be
# combined with the (now optional) text description -- at least one of the
# three is required, enforced in NeedCreateSerializer, not at the DB level.
# No real deployment exists yet (see DEPLOYMENT.md), so there's no
# production data to migrate/preserve here.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_wildfire_campaign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="need",
            name="media_file",
        ),
        migrations.RemoveField(
            model_name="need",
            name="media_moderation_status",
        ),
        migrations.RemoveField(
            model_name="need",
            name="media_type",
        ),
        migrations.AddField(
            model_name="need",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="need_media/"),
        ),
        migrations.AddField(
            model_name="need",
            name="video_moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="need",
            name="voice_file",
            field=models.FileField(blank=True, null=True, upload_to="need_media/"),
        ),
        migrations.AlterField(
            model_name="need",
            name="location_description",
            field=models.TextField(blank=True),
        ),
    ]
