# Generated by Django 5.2.17 on 2026-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_signalement_status_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalement",
            name="media_upload_errors",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="signalement",
            name="category",
            field=models.CharField(
                choices=[
                    ("electricity", "Poteau / câble électrique dangereux"),
                    ("pothole", "Nid-de-poule / trou"),
                    ("road", "Route dégradée"),
                    ("lighting", "Éclairage public"),
                    ("water", "Fuite d'eau"),
                    ("sewer", "Égouts"),
                    ("waste", "Ordures / déchets"),
                    ("signage", "Signalisation"),
                    ("danger", "Danger"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
