# Generated by Django 5.2.17 on 2026-09-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_signalement_media_errors_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalement",
            name="abuse_reports_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
