# Generated by Django 5.2.17 on 2026-09-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_simplify_contact_identity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconfiguration",
            name="admin_contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Shown site-wide (footer) when set. Leave blank to hide.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="admin_contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Shown site-wide (footer) when set. Leave blank to hide.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="category",
            field=models.CharField(
                choices=[("general", "General / contact"), ("bug", "Bug report")],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="requester_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="requester_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
