# Generated by Django 5.2.17 on 2026-09-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_signalement_abuse_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconfiguration",
            name="google_maps_api_key",
            field=models.CharField(
                blank=True,
                help_text="Google Maps *browser* key (it is sent to every visitor's browser, that's how Google Maps works): restrict it to HTTP referrer https://sosdz.org/* in Google Cloud, and set a daily quota + budget alert there.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="map_provider",
            field=models.CharField(
                choices=[("osm", "OpenStreetMap (free)"), ("google", "Google Maps")],
                default="osm",
                help_text="Map background and address suggestions for every map and address field. Google Maps needs the browser API key below (Maps JavaScript API + Places API (New) enabled, restricted to this site's domain). If Google fails for any reason, visitors automatically get OpenStreetMap instead.",
                max_length=10,
            ),
        ),
    ]
