# Generated by Django 5.2.17 on 2026-09-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_appconfiguration_map_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalement",
            name="extra_categories",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
