# Generated by Django 5.2.17 on 2026-09-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_admin_contact_and_bug_reports"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("ar", "العربية"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text='Dotted i18next key, e.g. "home.tagline"',
                        max_length=200,
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "ordering": ["locale", "key"],
                "unique_together": {("locale", "key")},
            },
        ),
    ]
