# Generated by Django 5.2.17 on 2026-09-01 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_translation_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appconfiguration",
            name="admin_contact_phone",
        ),
        migrations.CreateModel(
            name="AdminContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=30)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Optional, e.g. "WhatsApp" or a wilaya name',
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_phones",
                        to="core.appconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
