# Generated by Django 5.2.17 on 2026-09-01 15:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_admin_contact_phone_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="owner_token",
            field=models.CharField(
                default=core.models.generate_token,
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="need",
            name="recovery_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="pickup",
            name="recovery_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
