# Generated by Django 5.2.17 on 2026-09-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_comment_owner_token_need_recovery_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appconfiguration",
            name="media_moderation_active",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, uploaded photos/videos are auto-classified by the local NSFWJS sidecar (photos) and ffmpeg + NSFWJS (video frames) before being shown publicly; if either dependency isn't reachable/installed, the upload is queued as 'pending' for manual review here rather than silently published or rejected -- it is never fully automatic without both running (see README 'Moderation sidecar'). Turn this off to skip moderation entirely and auto-approve every upload immediately, e.g. if you don't want to run the sidecar/ffmpeg at all.",
            ),
        ),
    ]
