# Generated by Django 5.2.17 on 2026-09-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_appconfiguration_enforce_video_duration_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugReportProxy",
            fields=[],
            options={
                "verbose_name": "Bug report",
                "verbose_name_plural": "Bug reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.supportrequest",),
        ),
        migrations.CreateModel(
            name="RecoveryRequestProxy",
            fields=[],
            options={
                "verbose_name": "Recovery request (coordonnées oubliées)",
                "verbose_name_plural": "Recovery requests (coordonnées oubliées)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.supportrequest",),
        ),
    ]
