# Generated by Django 5.2.17 on 2026-09-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_bugreportproxy_recoveryrequestproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagephoto",
            name="moderated_by",
            field=models.CharField(
                blank=True,
                choices=[("system", "System"), ("admin", "Admin")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="deliveryphoto",
            name="moderated_by",
            field=models.CharField(
                blank=True,
                choices=[("system", "System"), ("admin", "Admin")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="need",
            name="video_moderated_by",
            field=models.CharField(
                blank=True,
                choices=[("system", "System"), ("admin", "Admin")],
                max_length=10,
            ),
        ),
    ]
