# Generated by Django 5.2.17 on 2026-09-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_damagephoto_moderated_by_deliveryphoto_moderated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionpoint",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="collectionpoint",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="collectionpoint",
            name="tiktok_url",
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
