# Generated by Django 5.2.17 on 2026-09-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_collectionpoint_facebook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionpoint",
            name="accepted_donations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="collectionpoint",
            name="other_phones",
            field=models.TextField(blank=True),
        ),
    ]
