# Generated by Django 5.2.17 on 2026-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_collectionpoint_accepted_donations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionpoint",
            name="flyer_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="collection_point_flyers/"
            ),
        ),
        migrations.AddField(
            model_name="collectionpoint",
            name="flyer_moderated_by",
            field=models.CharField(
                blank=True,
                choices=[("system", "System"), ("admin", "Admin")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="collectionpoint",
            name="flyer_moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
    ]
