# Generated by Django 5.2.17 on 2026-09-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_collectionpoint_flyer_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentreport",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("need_media_file", "Need media file (audio/video)"),
                    ("damage_photo", "Damage photo"),
                    ("delivery_photo", "Delivery photo"),
                    ("collection_point_flyer", "Collection point flyer"),
                ],
                max_length=30,
            ),
        ),
    ]
