# Generated by Django 5.2.17 on 2026-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_contentreport_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="need",
            name="other_phones",
            field=models.TextField(blank=True),
        ),
    ]
