# Generated by Django 5.2.17 on 2026-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_need_other_phones"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionpoint",
            name="recovery_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="collectionpoint",
            name="contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="collectionpoint",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="need",
            name="contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="need",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
