# Generated by Django 5.2.17 on 2026-09-03 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_collectionpoint_recovery_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickup",
            name="collection_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickups",
                to="core.collectionpoint",
            ),
        ),
        migrations.AlterField(
            model_name="pickup",
            name="need",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickups",
                to="core.need",
            ),
        ),
    ]
