# Generated by Django 5.2.17 on 2026-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_pickup_collection_point_alter_pickup_need"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickup",
            name="departure_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="pickup",
            name="departure_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pickup",
            name="departure_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
