# Generated by Django 5.2.17 on 2026-09-03 17:37, hand-adjusted: a plain
# AddField with a callable unique default only evaluates that callable once
# and reuses the same value for every existing row, which breaks the unique
# constraint on any table with more than one row (see the "Callable default
# on unique field" warning makemigrations raised for this exact field, and
# https://docs.djangoproject.com/en/5.2/howto/writing-migrations/#migrations-that-add-unique-fields).
# So this backfills a real per-row token before the unique constraint lands.
import core.models
from django.db import migrations, models


def backfill_access_tokens(apps, schema_editor):
    CollectionPoint = apps.get_model("core", "CollectionPoint")
    for point in CollectionPoint.objects.all():
        point.access_token = core.models.generate_token()
        point.save(update_fields=["access_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_pickup_departure_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionpoint",
            name="access_token",
            field=models.CharField(default=core.models.generate_token, editable=False, max_length=32, null=True),
        ),
        migrations.RunPython(backfill_access_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="collectionpoint",
            name="access_token",
            field=models.CharField(default=core.models.generate_token, editable=False, max_length=32, unique=True),
        ),
    ]
