# Generated by Django 5.2.17 on 2026-09-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_collectionpoint_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickup",
            name="responder_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
