# Generated by Django 5.2.17 on 2026-09-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_pickup_responder_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="pickup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.pickup",
            ),
        ),
    ]
