# Generated by Django 5.2.17 on 2026-09-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_comment_pickup"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionpoint",
            name="country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="collectionpoint",
            name="country_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="collectionpoint",
            name="wilaya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_points",
                to="core.wilaya",
            ),
        ),
    ]
