# Generated by Django 5.2.17 on 2026-09-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_collectionpoint_country_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionpoint",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
