# Generated by Django 5.2.17 on 2026-09-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_admincontactphone_audit_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admincontactphone",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="admincontactphone",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="collectionpoint",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="collectionpoint",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="damagephoto",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="damagephoto",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="deliveryphoto",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="deliveryphoto",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="disastertype",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="disastertype",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="duplicatereport",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="duplicatereport",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="locationping",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="locationping",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="need",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="need",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="pickup",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="pickup",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="progressupdate",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="progressupdate",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="translationoverride",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="translationoverride",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="wilaya",
            name="audit_creator_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="wilaya",
            name="audit_editor_country",
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
    ]
