# Generated by Django 5.2.17 on 2026-09-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_admincontactphone_audit_creator_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="need",
            name="has_no_location",
            field=models.BooleanField(default=False),
        ),
    ]
